### ISSUE TITLE
Aufgabenordner werden nicht angezeigt

### ISSUE THREAD

**Issue by Davka** [tgloeggl/studip-aufgaben#18]
Eine Dozenten hat Aufgaben erstellt und Ordner anlegen lassen. 
Nun hat Sie in die Ordner Feedbacks für die jeweilige Person hochgeladen, wobei der/die Student/in die Dateien nicht einsehen kann, weil der Ordner fehlt.

**Comment by tgloeggl** [comment]
fixed in #19
